version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
    # TODO: Should that be 27018?
      - "27018:27017"
    networks:
      - app-network
    restart: always

  books:
    # TODO: Check if it loads the image built from the first step
    build: books-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    restart: always
    depends_on:
      - mongodb

networks:
  app-network:
  
  
