# TODO: check the comments in the github website when running the workflow
name: assignment3
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log the time the workflow starts executing
        run: echo $(date -Iminutes) >> log.txt
      # Should add "/n" in the end of each line?
      - name: Log Submitters names
        run: echo Inbar Alfasi, Ofek Basson >> log.txt
      #Should build here only the books image?
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        # Does this push it to dockerhub? I didn't give the username+password
        uses: docker/build-push-action@v5
        with:
          context: ./books-service
          # What is the .setport?
          file: ./books-service/Dockerfile
          # Should I give that another name like in the lecture (gave it a name with a prefix of the username from github secrets)? Didn't do that
          # Should I save it also with the current time? Didn't do that
          # What is the "-v2" he used for in the example? He used it for build and push but not for the Upload artifact.
          tags: books-service:latest
          outputs: type=docker, dest=/tmp/image.tar
      - name: Log successful build
        if: success()
        run: echo image successfully built >> log.txt
      - name: Log unsuccessful build
        if: failure()
        run: echo image not able to be built >> log.txt        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: books-service
          path: /tmp/image.tar
        # Should be in the end of the workflow? Will it always work? Can I write to this file from different steps? Or I need to upload and downlowad it each step to add text to it?
      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
  test:
      # Should I specify on which machine it runs (did'nt do that in the second step in class)? do checkout? it is in the previous step
    runs-on: ubuntu-latest
    # What is that for?
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: books-service
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      # Necessary - I think it isn't. Good for debugging but not for production
      - name: Check books-service image is loaded
        run: docker image ls
      - name: Download log file
        uses: actions/download-artifact@v4
        with:
          name: log
          path: .
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
      - name: Run images in containers using docker-compose
        run: docker-compose up -d
      # Necessary - I think it isn't. Good for debugging but not for production
      - name: Check container is running
        run: docker ps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # TODO: Check if shell: /usr/bin/bash -e {0} that I get here is ok
      - name: Test with pytest
        run: |
          cd tests
          pytest -v assn3_tests.py >> assn3_test_results.txt
      - name: Upload test results
        # Should this always happen?
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: assn3_test_results
          # Should look like assn3_test_results.txt in the github repo? I think the .txt isn't shown
          path: tests/assn3_test_results.txt
  query:
    # Should I specify on which machine it runs (did'nt do that in the second step in class)? do checkout? it is in the previous step
    runs-on: ubuntu-latest
    # What is that for? Should I add write & build somehow?
    needs: test
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: books-service
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      # Necessary - I think it isn't. Good for debugging but not for production
      - name: Check books-service image is loaded
        run: docker image ls
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
      - name: Run images in containers using docker-compose
        run: docker-compose up -d
      # Necessary - I think it isn't. Good for debugging but not for production
      - name: Check container is running
        run: docker ps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # TODO: Check if shell: /usr/bin/bash -e {0} that I get here is ok
      - name: Execute POST requests
        run: | 
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"Adventures of Huckleberry Finn", "ISBN":"9780520343641", "genre":"Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"The Best of Isaac Asimov", "ISBN":"9780385050784", "genre":"Science Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"Fear No Evil", "ISBN":"9780394558783", "genre":"Biography"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"The Adventures of Tom Sawyer", "ISBN":"9780195810400", "genre":"Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN":"9780553294385", "genre":"Science Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN":"9780553293364", "genre":"Science Fiction"}'
      - name: Execute requests from query.txt
        run: |
          touch response.txt
          while read querystring; do
            response=$(curl -s -w "\n%{http_code}" "http://localhost:5001/books$querystring")
            body=$(echo "$response" | head -n -1)
            status_code=$(echo "$response" | tail -n 1)
            if [ "$status_code" -eq 200 ]; then
              echo "$querystring" >> response.txt
              echo "$body" >> response.txt
            else
              echo "$querystring" >> response.txt
              echo "error $status_code" >> response.txt
            fi
          done < query.txt
      - name: Upload response file
        # Should this always happen?
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: response
          path: response.txt