name: assignment3
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log the time the workflow starts executing
        run: echo $(date -Iminutes) >> log.txt
      # Should add "/n" in the end of each line?
      - name: Log Submitters names
        run: echo Inbar Alfasi, Ofek Basson >> log.txt
      #Should build here only the books image?
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        # Does this push it to dockerhub? I didn't give the username+password
        uses: docker/build-push-action@v5
        with:
          # What is the context?
          context: ./books-service
          # What is the .setport?
          file: ./books-service/Dockerfile
          # Should I give that another name like in the lecture (gave it a name with a prefix of the username from github secrets)? Didn't do that
          # Should I save it also with the current time? Didn't do that
          # What is the "-v2" he used for in the example? He used it for build and push but not for the Upload artifact.
          tags: books-service:latest
          outputs: type=docker, dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: books-service
          path: /tmp/image.tar
      # Remove?
      - name: List files for debugging
        run: ls -alh
        # Should be in the end of the workflow? Will it always work? Can I write to this file from different steps? Or I need to upload and downlowad it each step to add text to it?
      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
  test:
      # Shouldn I specify on which machine it runs (did'nt do that in the second step in class)? do checkout? it is in the previous step
    runs-on: ubuntu-latest
    # What is that for?
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: books-service
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Check books-service image is loaded
        run: docker image ls
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
      - name: Check directory
        run: pwd
      - name: List files in the repository root
        run: ls -la
      - name: Run images in containers using docker-compose
        run: docker-compose up -d
      - name: Check container is running
        run: docker ps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          cd tests
          ls
          pytest -v assn3_tests.py >> assn3_test_results.txt
          ls
      - name: Upload test results
        # Should this always happen?
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: assn3_test_results
          # Should look like assn3_test_results.txt in the github repo? I think the .txt isn't shown
          path: /tests/assn3_test_results.txt





  #query: